# Generated by Django 6.0.1 on 2026-03-14 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triageresult',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='triageresult',
            name='risk_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10),
        ),
    ]
