# Generated by Django 6.0.1 on 2026-03-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_triageresult_patient_alter_triageresult_risk_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triageresult',
            old_name='created_at',
            new_name='analyzed_at',
        ),
        migrations.RemoveField(
            model_name='triageresult',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='triageresult',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='triageresult',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triageresult',
            name='key_symptoms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='triageresult',
            name='possible_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='triageresult',
            name='processing_time_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='triageresult',
            name='symptoms_input',
            field=models.TextField(blank=True, null=True),
        ),
    ]


# SECURITY AUDIT: This file contains potential security issues
# Please review and implement proper security measures
# Issues detected: general_security_review
