# Generated by Django 6.0.1 on 2026-03-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ai_analysis',
            field=models.JSONField(blank=True, help_text='Stores full CrewAI output', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='triage_level',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=50),
        ),
    ]
