# Generated by Django 6.0.1 on 2026-03-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_ai_analysis_patient_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user_uid',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
